[2025-09-20 07:13:08] START attempt 1: python main.py --is_transfer True --test_dataset Computers --pretrained_model_name /mnt/data1/Graph/HypGraphLoRA/pre_trained_gnn/Cora.GRACE.GAT.hyp_True.True.20250912-232536.pth --few True --shot 10 --gpu_id 0
bash: line 1: python: command not found
[2025-09-20 07:13:08] END attempt 1: exit_code=127
[2025-09-20 07:13:18] START attempt 2: python main.py --is_transfer True --test_dataset Computers --pretrained_model_name /mnt/data1/Graph/HypGraphLoRA/pre_trained_gnn/Cora.GRACE.GAT.hyp_True.True.20250912-232536.pth --few True --shot 10 --gpu_id 0
bash: line 1: python: command not found
[2025-09-20 07:13:18] END attempt 2: exit_code=127
[2025-09-20 07:13:28] START attempt 3: python main.py --is_transfer True --test_dataset Computers --pretrained_model_name /mnt/data1/Graph/HypGraphLoRA/pre_trained_gnn/Cora.GRACE.GAT.hyp_True.True.20250912-232536.pth --few True --shot 10 --gpu_id 0
bash: line 1: python: command not found
[2025-09-20 07:13:28] END attempt 3: exit_code=127
