[2025-09-20 07:17:18] START attempt 1: python main.py --is_transfer True --test_dataset Photo --pretrained_model_name /mnt/data1/Graph/HypGraphLoRA/pre_trained_gnn/Photo.GRACE.GAT.hyp_True.True.20250912-232537.pth --few False --gpu_id 0
bash: line 1: python: command not found
[2025-09-20 07:17:18] END attempt 1: exit_code=127
[2025-09-20 07:17:28] START attempt 2: python main.py --is_transfer True --test_dataset Photo --pretrained_model_name /mnt/data1/Graph/HypGraphLoRA/pre_trained_gnn/Photo.GRACE.GAT.hyp_True.True.20250912-232537.pth --few False --gpu_id 0
bash: line 1: python: command not found
[2025-09-20 07:17:28] END attempt 2: exit_code=127
[2025-09-20 07:17:38] START attempt 3: python main.py --is_transfer True --test_dataset Photo --pretrained_model_name /mnt/data1/Graph/HypGraphLoRA/pre_trained_gnn/Photo.GRACE.GAT.hyp_True.True.20250912-232537.pth --few False --gpu_id 0
bash: line 1: python: command not found
[2025-09-20 07:17:38] END attempt 3: exit_code=127
